#! /bin/bash

CLASSPATH=.
for jar in ../jars/*.jar; do
	CLASSPATH=$CLASSPATH:$jar
done

export CLASSPATH

export ALECTORULES=rules.json

jruby --client -J-Dorg.eclipse.jetty.http.LEVEL=DEBUG shim_jetty.rb
