#! /bin/bash

# Tell the JVM to include all jars in lib subdir,
# after the current directory.
CLASSPATH="src:jarlib/*"

export CLASSPATH
export ALECTORULES=rules.json

echo Starting...
exec java\
 -Xms256m -Xmx256m -noverify -client\
 -Dorg.eclipse.jetty.http.LEVEL=DEBUG\
 org.jruby.Main src/_main.rb
